### ISSUE TITLE
DatabaseCleaner 1.7.0 incompatibility

### ISSUE THREAD

**Issue by rdh** [buildkite/test-collector-ruby#124]
After adding `buildkite-test_collector` to our Gemfile, [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner) has begun to fail when we call `DatabaseCleaner.clean`, it fails with the following error...

```
 NoMethodError:
            undefined method `-' for "2022-06-14 17:22:43 +0000":String
            Did you mean?  -@
```

**Comment by gchan** [comment]
Hi @rdh ! 

I noticed version 1.7.0 of DatabaseCleaner is a few versions behind. Have you tried upgrading to 2.0.1 or 1.99.0 and giving that a go?  We always aim to support the latest versions of common Ruby libraries. But there could be some configuration adjustments you can make to get it working on 1.7.0 if you are unable to upgrade.

Thanks!

**Comment by rdh** [comment]
Hmm, we can try upgrading, but in this case, it really seems like your gem is inadvertently turning a `Time` into a `String` in some system call that `DatabaseCleaner` relies on.  May be worth root causing on your end.

**Comment by gchan** [comment]
@rdh Yes, we strongly suggest upgrading to a more recent version for better a experience and developer support.

I've tried version 1.7.0 of `DatabaseCleaner` on a Rails app and wasn't able to reproduce the error. The issue may be specific to the code base you are working on. Do you have any further leads or details you could share?
